s042_14000417_django1/tamrin_asr/menu/urls.py
from django.urls import path
from . import views

app_name = "menu"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>', views.item_details, name='item_detail'),
]

s042_14000417_django1/tamrin_asr/tamrin_asr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls'))
]

s042_14000417_django1/tamrin_asr/core/models.py
from django.db import models
from model_utils.fields import AutoCreatedField, AutoLastModifiedField
from django.utils.translation import ugettext_lazy as _


# Django model utils TimeStampedModel
class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.

    """
    created = AutoCreatedField(_('created'))
    modified = AutoLastModifiedField(_('modified'))

    class Meta:
        abstract = True

s042_14000417_django1/tamrin_asr/menu/models.py
from django.db import models
from core.models import TimeStampedModel


# Create your models here.


class Category(TimeStampedModel):
    """
    create category for items
    """

    name = models.CharField(max_length=50)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"


class Price(TimeStampedModel):
    """
    price table
    """
    start_date = models.DateField()
    amount = models.IntegerField()

    def __str__(self):
        return f"price: {self.amount} |SD: {self.start_date}"


class Item(TimeStampedModel):
    """
    item model
    """
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.ForeignKey(Price, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

s042_14000417_django1/tamrin_asr/order/models.py
from django.db import models
from core.models import TimeStampedModel
from menu.models import Item
from table.models import Table

# Create your models here.
STATUS_ORDER = {
    ('P', 'Pending'),
    ('A', 'Accept'),
    ('R', 'Reject')
}

STATUS_RECEIPT = {
    ('N', 'Not Pay'),
    ('P', 'Pay')
}


class Order(TimeStampedModel):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.SET_NULL, blank=True, null=True)
    count = models.IntegerField()
    receipt = models.ForeignKey('Receipt', on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_ORDER, default='P')

    def __str__(self):
        return f"{self.id}|{self.item}"


class Receipt(TimeStampedModel):
    status = models.CharField(max_length=10, choices=STATUS_RECEIPT, default='N')

    @property
    def orders(self):
        return list(Order.objects.filter(receipt=self))

    @property
    def final_price(self):
        orders_price = list(map(lambda x: (x.item.price.amount * x.count), list(Order.objects.filter(receipt=self))))
        return sum(orders_price)

    def __str__(self):
        return f"{self.orders} | price: {self.final_price}$ "

s042_14000417_django1/tamrin_asr/table/models.py
from django.db import models
from core.models import TimeStampedModel

STATUS = {
    ('FR', 'free'),
    ('FU', 'full'),
    ('RE', 'reserve')

}


# Create your models here.

class Table(TimeStampedModel):
    """
    table model
    """

    name = models.CharField(max_length=30)
    capacity = models.IntegerField()
    status = models.CharField(max_length=10, choices=STATUS, default='FR')

    def __str__(self):
        return f"{self.name} | {self.capacity} sits | status: {self.status} "

s042_14000417_django1/tamrin_asr/menu/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item, Category


# Create your views here.


def index(request):
    items = Item.objects.all()
    categories = Category.objects.all
    context = {
        'items': items,
        'categories': categories
    }
    return render(request, template_name='menu/index.html', context=context)


def item_details(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    context = {
        'item': item
    }
    return render(request, template_name='menu/item/item.html', context=context)

s042_14000417_django1/tamrin_asr/order/views.py
from django.shortcuts import render

# Create your views here.

s042_14000417_django1/tamrin_asr/templates/menu/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        main {
            display: flex;
        }
    </style>

</head>
<body>
<h2>Category</h2>
<div style="width: 10%">

    <table>
        <tr>
            <th>
                Category name
            </th>

        </tr>
        {% for category in categories %}
            <tr>
                <td>
                    <a>{{ category.name }}</a>
                </td>

            </tr>
        {% endfor %}
    </table>
</div>

<h2>Items</h2>
<div style="width: 10%">

    <table>
        <tr>
            <th>
                Item name
            </th>

        </tr>
        {% for item in items %}
            <tr>
                <td>
                    <a href="{% url 'menu:item_detail' item.id %}">{{ item.name }}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>


</body>
</html>

s042_14000417_django1/tamrin_asr/templates/menu/item/item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        main {
            display: flex;
        }
    </style>

</head>
<body>

<h2>Items</h2>
<div style="width: 30%">

    <table>
        <tr>
            <th>
                Item name
            </th>
            <th>
                Category
            </th>
            <th>
                price
            </th>

        </tr>
        <tr>
            <td>
                <a>{{ item.name }}</a>
            </td>
            <td>
                {{ item.category }}
            </td>
            <td>
                {{ item.price.amount }}
            </td>
        </tr>
    </table>
</div>


</body>
</html>